Update DB on pkg remove
dappnode/DNP_DAPPMANAGER pull request #1532
Opened 2023-07-17 14:28 UTC by dsimog01

On pkg remove, the DB should be updated if that pkg was selected in the stakers tab

2023-07-20 12:43 UTC, 3alpha commented
Is there reason no to handle that here: https://github.com/dappnode/DNP_DAPPMANAGER/blob/develop/packages/dappmanager/src/calls/packageRemove.ts?

2023-07-21 07:16 UTC, pablomendezroyo requested changes

2023-07-21 07:16 UTC, pablomendezroyo commented on packages/dappmanager/src/daemons/stakerDbUpdate/index.ts
> +  if (!dnpNames) return;
this checker will not work as you expect. The `if(!...)` does not check for arrays with length 0. You must check for `if(dnpNames.length === 0)

2023-07-21 07:16 UTC, pablomendezroyo commented on packages/dappmanager/src/daemons/stakerDbUpdate/index.ts
> +  logger.info(`Removed clients/mev-boost ${dnpNames} from main DB`);
Too ambiguous and not precise. Not all packages might belong to the main DB. Either remove it or improve it

2023-07-21 07:16 UTC, pablomendezroyo commented on packages/dappmanager/src/daemons/stakerDbUpdate/index.ts
> +      case "mev-boost.dnp.dappnode.eth":
Use the dnpName provided by the library @dappnode/types

2023-07-21 09:28 UTC, merged