add zkevm rollup tab #1810
dappnode/DNP_DAPPMANAGER pull request #1811
Opened 2024-01-24 20:07 UTC by GiselleNessi

## Context

> Provide context of this PR: why it was created? what does it fixes? what new feature does it provides? ...

## Approach

> Define the solution for the issue or feature that this PR aims to fix

## Test instructions

2024-01-25 10:26 UTC, dappnodedev requested changes

2024-01-25 10:26 UTC, dappnodedev commented on packages/admin-ui/src/pages/rollups/components/RollupsRoot.tsx
> +      subPath: "zk",
`zk` is too generic

2024-01-25 10:32 UTC, dappnodedev commented on packages/admin-ui/src/pages/rollups/components/Zkevm.tsx
> +export default function Zkevm({ description }: { description: string }) {
Here you should:
1. Know whether the package is installed or not
2. If the package is installed, show it as selected if it is running and unselected if not
3. If the package is not installed, show it as unselected
4. If the user unselects the package and hits "apply", the package should be stopped
5. If the user selects the package and hits "apply" the package should be (installed) + started
6. If the package is installed and running, a button should be shown inside the card ("Go to UI")

To install the package you need to know its identifier, which is its `dnpName`. In this case, the `dnpName` of the package will be: `zkevm-tokens-withdrawal.dnp.dappnode.eth`

2024-02-12 14:59 UTC, closed without merging

2024-02-12 14:59 UTC, GiselleNessi commented
will open new PR for this issue