Gi/smooth modal
dappnode/DNP_DAPPMANAGER pull request #1855
Opened 2024-02-27 10:46 UTC by GiselleNessi

Show smooth modal

Please see issue #1808

<img width="1463" alt="Screenshot 2024-02-26 at 5 36 22 PM" src="https://github.com/dappnode/DNP_DAPPMANAGER/assets/53020124/75cec3ea-9204-4095-a723-c0a649ad14c8">

2024-02-27 14:34 UTC, Marketen reviewed
Everything related to Smooth looks correct

2024-02-27 15:16 UTC, Marketen commented
![Screenshot_20240227_161156](https://github.com/dappnode/DNP_DAPPMANAGER/assets/36164126/afafb043-0b1b-42f6-aac1-64e8929fcf0b)
![Screenshot_20240227_161550](https://github.com/dappnode/DNP_DAPPMANAGER/assets/36164126/6f21ab65-fa3e-47d0-9f99-dd750aefc3f8)

when I switch my dappmanager to this branch, some popup texts appear with wrong sizes, unsure if its related to these changes

2024-02-27 15:20 UTC, Marketen requested changes

2024-02-27 15:20 UTC, Marketen commented on packages/admin-ui/src/components/smooth.scss
> +.title {
i would change this identifier to something more "smooth related" not that generic

2024-02-27 15:20 UTC, Marketen commented on packages/admin-ui/src/components/smooth.scss
> +.description {
this one too

2024-02-27 17:24 UTC, Marketen approved these changes
LGTM

2024-03-04 09:05 UTC, pablomendezroyo approved these changes

2024-03-04 09:05 UTC, merged