Add dappnode peer to production IPFS node
dappnode/DNP_DAPPMANAGER pull request #1915
Opened 2024-04-09 09:02 UTC by mateumiralles

Updating `addDappnodePeerToLocalIpfsNode()` to `addDappnodePeerToIpfsNodes()` to also add the dappnode peer to production the production IPFS node.

2024-04-09 09:32 UTC, pablomendezroyo requested changes

2024-04-09 09:32 UTC, pablomendezroyo commented on packages/migrations/src/addDappnodePeerToIpfsNodes.ts
> +  nodesIps.forEach(async (node) => {
Using forEach with asynchronous operations can lead to unexpected behaviors and difficulties in managing control flow. Please use other control flow like for const of or Promise.all

2024-04-09 09:32 UTC, pablomendezroyo commented on packages/migrations/src/addDappnodePeerToIpfsNodes.ts
> +    "167.86.114.131", //local node
This is not local but remote - dev/testing node

2024-04-09 09:32 UTC, pablomendezroyo commented on packages/migrations/src/addDappnodePeerToIpfsNodes.ts
> +    "65.109.51.31", //production node
remote production

2024-04-09 09:32 UTC, pablomendezroyo commented on packages/migrations/src/addDappnodePeerToIpfsNodes.ts
> +    `/ip4/${ipfsNodeIp}/tcp/4001/p2p/QmfB6dT5zxUq1BXiXisgcZKYkvjywdDYBK5keRaqDKH633`;
Are you sure it works like this? each IPFS node has a different ID, so production and dev nodes have a different node ID 

Checkout https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-swarm-peering-add

2024-04-10 07:45 UTC, pablomendezroyo approved these changes

2024-04-10 07:45 UTC, 3alpha commented
Pls do not add production node here, dev is enough.

2024-04-10 10:01 UTC, pablomendezroyo commented
Not required :(

2024-04-10 10:01 UTC, closed without merging