Add telegram user ID
dappnode/DNP_DAPPMANAGER pull request #1918
Opened 2024-04-10 08:15 UTC by pablomendezroyo

Add telegram user ID and use to only allow commands from this user

2024-04-10 09:45 UTC, 3alpha requested changes

2024-04-10 09:45 UTC, 3alpha commented on packages/db/src/system.ts
> +const TELEGRA_USER_ID = "telegram-user-id";
```suggestion
const TELEGRAM_USER_ID = "telegram-user-id";
```

2024-04-10 09:45 UTC, 3alpha commented on packages/db/src/system.ts
> +export const telegramUserId = dbMain.staticKey<string>(TELEGRA_USER_ID, "");
```suggestion
export const telegramUserId = dbMain.staticKey<string>(TELEGRAM_USER_ID, "");
```

2024-04-17 13:51 UTC, pablomendezroyo commented on packages/daemons/src/telegramBot/dappnodeTelegramBot.ts
> +            const deviceName = msg.text.split(" ")[1] || "dappnode_admin";
like what

2024-04-17 13:54 UTC, pablomendezroyo commented on packages/daemons/src/telegramBot/dappnodeTelegramBot.ts
> +  private async getWireguardCredentialsCmd(
true, but the src code is in the  dappmanager module. Ideal solution should be create a separated module for wireguard and use it either in dappmanager and here

2024-04-22 10:07 UTC, mateumiralles commented on packages/admin-ui/src/pages/system/components/Notifications/Telegram.tsx
> +        <Input
Using `<InputSecret/>` instead of `<Input/>`?

2024-04-22 13:00 UTC, merged