Pablo docker timeout
dappnode/DNP_DAPPMANAGER pull request #423
Opened 2020-10-30 13:24 UTC by pablomendezroyo

**Added timeout parameter to:**
- `dockerComposeUp():` called in restartPackage, restartPackageVolumes, rollbackPackages, runPackages, and tests.
- `dockerComposeDown():` called in packageRemove and tests.
- `dockerComposeStop():` no needed to change anything in the background since it is not called anywhere.
- `dockerStop():` called in packageStartStop and tests.

**Added new funtion:**
- `getDockerTimeoutMax():` this function returns the maximum timeout value from all the docker packages, in order to be used in the corersponding place.

**Other changes**
These changes were implemented after running yarn build
- Due to the delete of the timeout parameter in some functions in the previous commit, there have appeared some errors due to functions calls with this parameter. There have been deleted the timeout parameter in these function calls.
- Added timeout parameter to coreUpdatePackageData()
- Give undefined value to timeout parameter in getInstallerPackageData()

2020-10-30 16:37 UTC, pablomendezroyo commented
no more tests errors found

2020-11-03 08:11 UTC, dapplion requested changes

2020-11-03 08:11 UTC, dapplion commented on packages/dappmanager/src/modules/docker/utils.ts
> +import { PackageContainer } from "../../common";
PLease import from types not common

2020-11-03 08:11 UTC, dapplion commented on packages/dappmanager/src/modules/docker/restartPackageVolumes.ts
> +import { listPackage, listPackages } from "./listContainers";
If listPackage is not used please remove it

2020-11-03 08:16 UTC, dapplion approved these changes

2020-11-03 08:45 UTC, merged