Fix copy wireguard button
dappnode/DNP_DAPPMANAGER pull request #958
Opened 2022-02-10 09:46 UTC by pablomendezroyo

- Fixes copy config button: https://github.com/dappnode/DNP_DAPPMANAGER/issues/862

2022-02-14 11:32 UTC, 3alpha approved these changes

2022-02-18 03:18 UTC, dapplion approved these changes

2022-02-18 03:18 UTC, dapplion requested changes
Wait, @pablomendezroyo let's review this one together

2022-02-26 06:55 UTC, alexpeterson91 commented
> > Wait, @pablomendezroyo let's review this one together
> 
> 
> 
> lets merge this and fix the promis never resolves issue in the future

Fully agreed I've been having issues with this for a while and it's come up in support a lot. @dapplion Please agree to push through and merge.

2022-03-02 11:34 UTC, dapplion approved these changes
Okay LGTM

2022-03-02 14:14 UTC, merged